# Generated by Django 6.0.1 on 2026-01-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=30)),
                ('image_file_name', models.CharField(blank=True, max_length=255)),
                ('image_url', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '객체 탐지 이미지',
                'verbose_name_plural': '객체 탐지 이미지 목록',
                'db_table': 'vision_image',
                'ordering': ['sort_order', '-id'],
                'indexes': [models.Index(fields=['room_type'], name='vision_imag_room_ty_b09ef2_idx'), models.Index(fields=['created_at'], name='vision_imag_created_e14c4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yolo_id', models.IntegerField(blank=True, null=True)),
                ('yolo_class', models.CharField(max_length=50)),
                ('confidence', models.DecimalField(decimal_places=5, max_digits=6)),
                ('bbox_x', models.DecimalField(decimal_places=6, max_digits=8)),
                ('bbox_y', models.DecimalField(decimal_places=6, max_digits=8)),
                ('bbox_w', models.DecimalField(decimal_places=6, max_digits=8)),
                ('bbox_h', models.DecimalField(decimal_places=6, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_detections', to='policy.furniture')),
                ('vision_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='vision.visionimage')),
            ],
            options={
                'verbose_name': '객체 탐지 결과',
                'verbose_name_plural': '객체 탐지 결과 목록',
                'indexes': [models.Index(fields=['vision_image'], name='vision_dete_vision__5031a1_idx'), models.Index(fields=['furniture'], name='vision_dete_furnitu_673f6e_idx'), models.Index(fields=['yolo_class'], name='vision_dete_yolo_cl_910fee_idx'), models.Index(fields=['-created_at'], name='vision_dete_created_d43349_idx')],
            },
        ),
    ]
