# Generated by Django 6.0.1 on 2026-01-24 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policy', '0001_initial'),
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('move_type', models.CharField(choices=[('GENERAL', 'GENERAL'), ('PACKING', 'PACKING')], max_length=20)),
                ('area', models.IntegerField()),
                ('origin_address', models.TextField()),
                ('origin_floor', models.IntegerField()),
                ('origin_has_elevator', models.BooleanField(default=False)),
                ('origin_use_ladder', models.BooleanField(default=False)),
                ('dest_address', models.TextField()),
                ('dest_floor', models.IntegerField()),
                ('dest_has_elevator', models.BooleanField(default=False)),
                ('dest_use_ladder', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('recommended_ton', models.IntegerField()),
                ('special_item_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'estimate',
                'indexes': [models.Index(fields=['move_type'], name='estimate_move_ty_22a467_idx'), models.Index(fields=['created_at'], name='estimate_created_d76b8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstimatePrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('calculated_at', models.DateTimeField()),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='estimates.estimate')),
            ],
            options={
                'db_table': 'estimate_price',
            },
        ),
        migrations.CreateModel(
            name='EstimatePriceSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('BASE', 'BASE'), ('LADDER', 'LADDER'), ('STAIRS', 'STAIRS'), ('DISTANCE', 'DISTANCE'), ('SPECIAL', 'SPECIAL')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('estimate_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='estimates.estimateprice')),
            ],
            options={
                'db_table': 'estimate_price_section',
            },
        ),
        migrations.CreateModel(
            name='EstimatePriceLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope', models.CharField(blank=True, choices=[('ORIGIN', 'ORIGIN'), ('DEST', 'DEST')], max_length=10, null=True)),
                ('name_kr', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('furniture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_price_lines', to='policy.furniture')),
                ('estimate_price_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='estimates.estimatepricesection')),
            ],
            options={
                'db_table': 'estimate_price_line',
            },
        ),
        migrations.CreateModel(
            name='EstimateRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=30)),
                ('image_url', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='estimates.estimate')),
                ('vision_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_rooms', to='vision.visionimage')),
            ],
            options={
                'db_table': 'estimate_room',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('w_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('h_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('padding_cm', models.DecimalField(decimal_places=1, max_digits=4)),
                ('packed_w_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('packed_d_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('packed_h_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stackable', models.BooleanField(default=False)),
                ('can_stack_on_top', models.BooleanField(default=False)),
                ('allowed_rotations_json', models.JSONField(default=list)),
                ('needs_disassembly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='policy.furniture')),
                ('estimate_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimates.estimateroom')),
            ],
            options={
                'db_table': 'estimate_item',
            },
        ),
        migrations.CreateModel(
            name='EstimateTruckPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('truck_type', models.CharField(max_length=20)),
                ('truck_count', models.IntegerField()),
                ('inner_w_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inner_d_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inner_h_cm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_plans', to='estimates.estimate')),
            ],
            options={
                'db_table': 'estimate_truck_plan',
            },
        ),
        migrations.AddIndex(
            model_name='estimatepricesection',
            index=models.Index(fields=['estimate_price'], name='estimate_pr_estimat_e39e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatepricesection',
            index=models.Index(fields=['key'], name='estimate_pr_key_e50c34_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatepriceline',
            index=models.Index(fields=['estimate_price_section'], name='estimate_pr_estimat_e96248_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatepriceline',
            index=models.Index(fields=['scope'], name='estimate_pr_scope_16f1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatepriceline',
            index=models.Index(fields=['furniture'], name='estimate_pr_furnitu_52ad65_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateroom',
            index=models.Index(fields=['estimate'], name='estimate_ro_estimat_a3b640_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateroom',
            index=models.Index(fields=['vision_image'], name='estimate_ro_vision__19bb88_idx'),
        ),
        migrations.AddConstraint(
            model_name='estimateroom',
            constraint=models.UniqueConstraint(fields=('estimate', 'sort_order'), name='uq_estimate_room_estimate_sort_order'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['estimate_room'], name='estimate_it_estimat_2305be_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['furniture'], name='estimate_it_furnitu_7af9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='estimateitem',
            index=models.Index(fields=['item_id'], name='estimate_it_item_id_0bd029_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatetruckplan',
            index=models.Index(fields=['estimate'], name='estimate_tr_estimat_824db8_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatetruckplan',
            index=models.Index(fields=['truck_type'], name='estimate_tr_truck_t_fa9253_idx'),
        ),
    ]
