# Generated by Django 6.0.1 on 2026-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='recommended_ton',
            field=models.DecimalField(decimal_places=1, help_text='추천 적재 톤수 (예: 6.0, 7.5, 10.0)', max_digits=4),
        ),
    ]
