# Generated by Django 6.0.1 on 2026-01-25 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0002_alter_estimate_recommended_ton'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='load_factor_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='총 적재율(%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimate',
            name='remaining_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='총 남은 용량(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimate',
            name='total_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='가구+박스 총 부피(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimate',
            name='truck_capacity_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='선택된 트럭 조합 총 용량(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimatetruckplan',
            name='capacity_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='이 트럭 용량(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimatetruckplan',
            name='load_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='이 트럭 배정 적재량(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimatetruckplan',
            name='load_factor_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='이 트럭 적재율(%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='estimatetruckplan',
            name='remaining_cbm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='이 트럭 남은 용량(CBM)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
