# Generated by Django 6.0.1 on 2026-01-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0003_estimate_load_factor_pct_estimate_remaining_cbm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='box_rule_note',
            field=models.CharField(blank=True, help_text='적용된 박스 룰 설명(note)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='boxes_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='평수 룰로 산정된 박스 개수(boxes_avg)', null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='special_item_count',
            field=models.IntegerField(default=0, help_text='특수가구 개수'),
        ),
    ]
