# Generated by Django 6.0.1 on 2026-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_estimate_box_rule_note_estimate_boxes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='box_rule_note',
        ),
        migrations.AddField(
            model_name='estimate',
            name='boxes_description',
            field=models.CharField(blank=True, help_text='박스 산정 근거 설명', max_length=255, null=True),
        ),
    ]
