# Generated by Django 6.0.1 on 2026-01-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0005_remove_estimate_box_rule_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimateprice",
            name="calculated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
