# Generated by Django 6.0.1 on 2026-01-27 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0006_alter_estimateprice_calculated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estimate",
            options={
                "verbose_name": "견적 정보",
                "verbose_name_plural": "1. 견적 정보 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimateitem",
            options={
                "verbose_name": "이삿짐 아이템",
                "verbose_name_plural": "4. 이삿짐 아이템 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimateprice",
            options={
                "verbose_name": "견적 비용",
                "verbose_name_plural": "5. 견적 비용 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatepriceline",
            options={
                "verbose_name": "견적 세부비용 내역",
                "verbose_name_plural": "7. 견적 세부비용 내역 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatepricesection",
            options={
                "verbose_name": "견적 세부비용",
                "verbose_name_plural": "6. 견적 세부비용 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimateroom",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "공간(방) 정보",
                "verbose_name_plural": "3. 공간(방) 정보 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="estimatetruckplan",
            options={
                "verbose_name": "이사 차량",
                "verbose_name_plural": "2. 이사 차량 목록",
            },
        ),
    ]
