# Generated by Django 6.0.1 on 2026-01-27 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "estimates",
            "0007_alter_estimate_options_alter_estimateitem_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estimate",
            name="boxes_count",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="boxes_description",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="distance_km",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="load_factor_pct",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="recommended_ton",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="remaining_cbm",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="special_item_count",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="total_cbm",
        ),
        migrations.RemoveField(
            model_name="estimate",
            name="truck_capacity_cbm",
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="boxes_count",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="평수 룰로 산정된 박스 개수(boxes_avg)", null=True
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="boxes_description",
            field=models.CharField(
                blank=True, help_text="박스 산정 근거 설명", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="거리(km)",
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="load_factor_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="총 적재율(%)",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="recommended_ton",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="추천 적재 톤수 (예: 6.0, 7.5, 10.0)",
                max_digits=4,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="remaining_cbm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="총 남은 용량(CBM)",
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="special_item_count",
            field=models.IntegerField(default=0, help_text="특수가구 개수"),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="total_cbm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="가구+박스 총 부피(CBM)",
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="estimateprice",
            name="truck_capacity_cbm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="선택된 트럭 조합 총 용량(CBM)",
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="estimateprice",
            name="estimate",
            field=models.OneToOneField(
                help_text="총 요금",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price",
                to="estimates.estimate",
            ),
        ),
        migrations.AlterField(
            model_name="estimateprice",
            name="total_amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="estimatepriceline",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="estimatepricesection",
            name="amount",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="estimatetruckplan",
            name="truck_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="estimateprice",
            index=models.Index(
                fields=["calculated_at"], name="estimate_pr_calcula_8fbf84_idx"
            ),
        ),
    ]
