# Generated by Django 6.0.1 on 2026-01-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0008_remove_estimate_boxes_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="dest_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="dest_floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="dest_has_elevator",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="estimate",
            name="dest_use_ladder",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
