# Generated by Django 6.0.1 on 2026-01-27 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0009_alter_estimate_dest_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimateprice",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="거리(km)",
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
