# Generated by Django 6.0.1 on 2026-01-24 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_min_py",
                    models.PositiveSmallIntegerField(
                        help_text="구간 시작 평수 (포함)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "area_max_py",
                    models.PositiveSmallIntegerField(
                        help_text="구간 끝 평수 (포함)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("boxes_min", models.PositiveSmallIntegerField(help_text="박스 최소")),
                ("boxes_max", models.PositiveSmallIntegerField(help_text="박스 최대")),
                ("boxes_avg", models.PositiveSmallIntegerField(help_text="기본값")),
                (
                    "note",
                    models.CharField(help_text="평수 표시용 라벨", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "평수별 박스 개수",
                "verbose_name_plural": "3. 평수별 박스 개수 목록",
                "ordering": ("area_min_py",),
            },
        ),
        migrations.CreateModel(
            name="BasePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "GENERAL(일반이사)"),
                            ("PACKING", "PACKING(포장이사)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "truck_type",
                    models.CharField(
                        choices=[
                            ("1T", "1T"),
                            ("2_5T", "2_5T"),
                            ("5T", "5T"),
                            ("6T", "6T"),
                            ("7_5T", "7.5T"),
                            ("10T", "10T"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "base_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("included_workers", models.PositiveSmallIntegerField(default=0)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="기준 인원 작성 (예: 남5+여2)",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "기본 요금",
                "verbose_name_plural": "5. 기본 요금 목록",
                "indexes": [
                    models.Index(
                        fields=["move_type", "truck_type"],
                        name="policy_base_move_ty_457da7_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_base_is_acti_15f5ff_idx"
                    ),
                ],
                "unique_together": {("move_type", "truck_type")},
            },
        ),
        migrations.CreateModel(
            name="DistanceFeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "truck_type",
                    models.CharField(
                        choices=[
                            ("1T", "1T"),
                            ("2_5T", "2_5T"),
                            ("5T", "5T"),
                            ("6T", "6T"),
                            ("7_5T", "7.5T"),
                            ("10T", "10T"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("base_km", models.PositiveSmallIntegerField(default=20)),
                ("unit_km", models.PositiveSmallIntegerField(default=10)),
                (
                    "per_unit_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "거리 요금",
                "verbose_name_plural": "8. 거리 요금 목록",
                "indexes": [
                    models.Index(
                        fields=["truck_type"], name="policy_dist_truck_t_aef99d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_dist_is_acti_b9654d_idx"
                    ),
                ],
                "unique_together": {("truck_type", "base_km", "unit_km")},
            },
        ),
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL_APPLIANCE", "GENERAL_APPLIANCE (일반가전)"),
                            ("KITCHEN_APPLIANCE", "KITCHEN_APPLIANCE (주방가전)"),
                            ("GENERAL_FURNITURE", "GENERAL_FURNITURE (일반가구)"),
                            ("SPECIAL_FURNITURE", "SPECIAL_FURNITURE (특수가구)"),
                            ("ETC", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("yolo_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name_en", models.CharField(max_length=64, unique=True)),
                ("name_kr", models.CharField(max_length=64)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "width_cm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "depth_cm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "padding_cm",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        help_text="포장재 두께(cm, 사방 적용)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("needs_disassembly", models.BooleanField(default=False)),
                (
                    "stackable",
                    models.BooleanField(
                        default=False,
                        help_text="이 물건을 다른 물건 위에 올릴 수 있는지 (True=다른 물건 위에 쌓아도 됨 / False=다른 물건 위에 쌓으면 안됨)",
                    ),
                ),
                (
                    "can_stack_on_top",
                    models.BooleanField(
                        default=False,
                        help_text="이 물건 위에 다른 걸 올려도 되는지 여부 (True=위에 다른물건을 올려도 됨 / False=위에 다른 물건을 올릴 수 없음)",
                    ),
                ),
            ],
            options={
                "verbose_name": "가구",
                "verbose_name_plural": "1. 가구 목록",
                "indexes": [
                    models.Index(
                        fields=["category"], name="policy_furn_categor_c5a7cc_idx"
                    ),
                    models.Index(
                        fields=["name_en"], name="policy_furn_name_en_1f6b53_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LadderFeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ladder_truck_group",
                    models.CharField(
                        choices=[
                            ("1T", "1T"),
                            ("2_5T", "2_5T"),
                            ("5T", "5T"),
                            ("6T", "6T"),
                            ("7_5T", "7.5T"),
                            ("10T", "10T"),
                        ],
                        max_length=10,
                    ),
                ),
                ("floor_from", models.PositiveSmallIntegerField()),
                ("floor_to", models.PositiveSmallIntegerField()),
                (
                    "base_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "사다리차 요금",
                "verbose_name_plural": "6. 사다리차 요금 목록",
                "indexes": [
                    models.Index(
                        fields=["ladder_truck_group", "floor_from", "floor_to"],
                        name="policy_ladd_ladder__5d2c09_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_ladd_is_acti_1b8837_idx"
                    ),
                ],
                "unique_together": {("ladder_truck_group", "floor_from", "floor_to")},
            },
        ),
        migrations.CreateModel(
            name="StairsFeeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_from", models.PositiveSmallIntegerField()),
                ("floor_to", models.PositiveSmallIntegerField()),
                (
                    "per_floor_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "계단 요금",
                "verbose_name_plural": "7. 계단 요금 목록",
                "indexes": [
                    models.Index(
                        fields=["floor_from", "floor_to"],
                        name="policy_stai_floor_f_db593d_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_stai_is_acti_cd5f5a_idx"
                    ),
                ],
                "unique_together": {("floor_from", "floor_to")},
            },
        ),
        migrations.CreateModel(
            name="TruckSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "truck_type",
                    models.CharField(
                        choices=[
                            ("1T", "1T"),
                            ("2_5T", "2_5T"),
                            ("5T", "5T"),
                            ("6T", "6T"),
                            ("7_5T", "7.5T"),
                            ("10T", "10T"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "body_type",
                    models.CharField(
                        choices=[("CARGO", "CARGO(카고)"), ("TOP", "TOP(탑차)")],
                        max_length=10,
                    ),
                ),
                (
                    "inner_width_cm",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "inner_length_cm",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "inner_height_cm",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "cbm_geom",
                    models.PositiveSmallIntegerField(
                        help_text="세제곱미터, 1CBM = 1m*1m*1m",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "트럭 적재함 스펙",
                "verbose_name_plural": "4. 트럭 적재함 스펙 목록",
                "indexes": [
                    models.Index(
                        fields=["truck_type"], name="policy_truc_truck_t_78a0f2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_truc_is_acti_2ac1c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FurnitureRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orientation_code",
                    models.CharField(
                        choices=[
                            ("WHD", "WHD (바닥면=WXH, 높이=D)"),
                            ("WDH", "WDH (바닥면=WXD, 높이=H)"),
                            ("HWD", "HWD (바닥면=HXW, 높이=D)"),
                            ("HDW", "HDW (바닥면=HXD, 높이=W)"),
                            ("DWH", "DWH (바닥면=DXW, 높이=H)"),
                            ("DHW", "DHW (바닥면=DXH, 높이=W)"),
                        ],
                        max_length=3,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "furniture",
                    models.ForeignKey(
                        db_column="furniture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotations",
                        to="policy.furniture",
                    ),
                ),
            ],
            options={
                "verbose_name": "가구 회전",
                "verbose_name_plural": "2. 가구 회전 목록",
                "indexes": [
                    models.Index(
                        fields=["furniture"], name="policy_furn_furnitu_3fa018_idx"
                    ),
                    models.Index(
                        fields=["orientation_code"],
                        name="policy_furn_orienta_fb1318_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("furniture", "orientation_code"),
                        name="uq_policy_furniture_rotation_furniture_orientation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecialItemFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "unit_amount",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "furniture",
                    models.ForeignKey(
                        db_column="furniture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_fees",
                        to="policy.furniture",
                    ),
                ),
            ],
            options={
                "verbose_name": "특수가구 요금",
                "verbose_name_plural": "9. 특수가구 요금 목록",
                "indexes": [
                    models.Index(
                        fields=["furniture"], name="policy_spec_furnitu_d484bd_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="policy_spec_is_acti_fe5d23_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("furniture",), name="uq_special_fee_furniture"
                    )
                ],
            },
        ),
    ]
