# Generated by Django 6.0 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("publication_date", models.DateField()),
                ("price", models.IntegerField()),
            ],
            options={
                "verbose_name": "도서",
                "verbose_name_plural": "도서 목록",
            },
        ),
    ]
