# Generated by Django 6.0 on 2025-12-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Example",
        ),
    ]
