# Generated by Django 6.0 on 2025-12-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_rename_book_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': '예시 데이터', 'verbose_name_plural': '예시 목록'},
        ),
    ]
